### ISSUE TITLE
What does rewards in rollouts mean?

### ISSUE THREAD

**Issue by nuomizai** [mingzhangPHD/Adversarial-Imitation-Learning#2]
Hi, @mingzhangPHD . I appreciated your idea but got confused when reading the code. In `WDAIL/ppo_wdail_BL/tools/learn.py`, I found that you reassigned the value of `rollouts.rewards` with `discriminator` (in line 746) after rollout updated with the extrinsic real reward (in line 702). So, do you need the extrinsic reward for the update of Wasserstein-based discriminator or the update of PPO policy?

**Comment by mingzhangPHD** [comment]
The original idea of DIR is to use the discriminator instead of general rewards. I don't use the extrinsic reward to update the ppo policy. The general rewards in rollouts. rewards just a standard function which is easier for me to use. You could check the update function. The output of the discriminator is used as reward to update the PPO policy.

**Comment by nuomizai** [comment]
> I don't use the extrinsic reward to update the ppo policy. The general rewards in rollouts. rewards just a standard function which is easier for me to use. You could check the update function. The output of the discriminator is used as reward to update the PPO policy.

Got it. Thanks for your reply!
